# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Connectivity tools
email: ben.lansdell@gmail.com
description: > # this means to ignore newlines until "baseurl:"
MATLAB and python tools for inferring connectivity in spike trains based 
primarily around generalized linear models (GLMs). 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://benlansdell.github.io/connectivity" # the base hostname & protocol for your site
github_username:  benlansdell

# Build settings
markdown: kramdown
